### ISSUE TITLE
Lightbox not working

### ISSUE THREAD

**Issue by matthewolckers** [mfg92/hugo-shortcode-gallery#1]
Hi Matze. Firstly, thank you the help on https://github.com/vickylai/hugo-theme-sam/issues/26 . Your shortcode has saved me a lot of time. 

I am having trouble with the lightbox and I think you might have the same problem. When I visit https://matze.rocks/images/ and click on the image the lightbox opens but its just blank with no image. 

Any idea what the problem is?

**Comment by mfg92** [comment]
I have fixed it! :)
