### ISSUE TITLE
How to change the exif tag?

### ISSUE THREAD

**Issue by faaafo** [mfg92/hugo-shortcode-gallery#11]
Changing from `{{ .Model }}` to `{{ .Quality }}` displays nothing instead of expected tag value (RAW for this particular tag). Tried other tags as well, nothing. Any ideas?

https://github.com/mfg92/hugo-shortcode-gallery/blob/8a43186e78d4a9ceb114b6bdb6299fa005b23c21/layouts/shortcodes/gallery.html#L114

Tested with https://raw.githubusercontent.com/mfg92/hugo-shortcode-gallery/example_site/example_site/content/gallery/images/2020-07-26-_MG_3439.jpg :heart_eyes: 

Adding these two lines to `config.toml` don't change the issue:

```toml
[imaging.exif]
includeFields = ".*"
```

Update:
- Found one tag working: Artist

**Comment by mfg92** [comment]
It seems there is no metadata "Quality" available.

You can see all available metadata if you add this line to line 112 of _layouts/shortcodes/gallery.html_:
`data-all-metadata="{{.}}"`

Then you can see all available metadata in the generated HTML sourcode of your page. The result for the mentioned image is this:

`data-all-metadata="map[ApertureValue:6.625 Artist:MFG ColorSpace:1 ComponentsConfiguration: Copyright:MFG CustomRendered:0 DateTime:2020-10-21 19:20:03 &#43;0200 CEST DateTimeDigitized:2020-07-26 17:22:36 &#43;0200 CEST DateTimeOriginal:2020-07-26 17:22:36 &#43;0200 CEST ExifIFDPointer:330 ExifVersion:0230 ExposureBiasValue:0 ExposureMode:1 ExposureProgram:1 ExposureTime:1/400 FNumber:10 Flash:16 FlashpixVersion:0100 FocalLength:400 FocalPlaneResolutionUnit:2 FocalPlaneXResolution:6514.657980456026 FocalPlaneYResolution:6734.006734006734 GPSInfoIFDPointer:39324 GPSLatitude:[49 35.979766 0] GPSLatitudeRef:N GPSLongitude:[11 0.426635 0] GPSLongitudeRef:E GPSVersionID:[2 2 0 0] ISOSpeedRatings:500 ImageDescription:Water lily InteroperabilityIFDPointer:39294 InteroperabilityIndex:R98 LensModel:EF100-400mm f/4.5-5.6L IS II USM Make:Canon MakerNote: MeteringMode:5 Model:Canon EOS 80D Orientation:1 PixelXDimension:800 PixelYDimension:534 ResolutionUnit:2 SceneCaptureType:0 ShutterSpeedValue:8.625 Software:darktable 3.2.1 SubSecTime:00 SubSecTimeDigitized:00 SubSecTimeOriginal:00 Tags:[macro published|matze.rocks plant|flower|water lily] WhiteBalance:0 XResolution:300 YResolution:300]"`

If you need some additional metadata you can use a meta sidecar file (see https://github.com/mfg92/hugo-shortcode-gallery/blob/master/README.md). Like:
```JSON
{
    "ImageDescription": "Water lily",
    "Tags":["macro","published|matze.rocks","plant|flower|water lily"],
    "Quality":85
}
```

Here you can find some background information: https://gohugo.io/content-management/image-processing/#exif
Note that `$metadata` in _layouts/shortcodes/gallery.html_ is (more or less) equals to `src.Exif.Tags` from the documentation.

**Comment by faaafo** [comment]
Thanks. Somehow I can't workout the exif engine/standard Hugo's using. `efixtool` returns **Quality : RAW**
```sh
wget \
https://raw.githubusercontent.com/mfg92/hugo-shortcode-gallery/example_site/example_site/content/gallery/images/2020-07-26-_MG_3439.jpg \
--quiet \
-O x.jpg; \
exiftool x.jpg \
| grep -e "^Quality"
```

`Quality                         : RAW`
