### ISSUE TITLE
rowHeight not used if row is not filled

### ISSUE THREAD

**Issue by think-nice-things** [mfg92/hugo-shortcode-gallery#23]
If I've a very low number of images, say only one or two, than the images are displayed full size accross the page width even though they should be limited by rowHeight.
Would it be possible that the images always have a height not larger than rowHeight?

**Comment by mfg92** [comment]
You can use the parameter `lastRow` to define what should happen to the images of the last row. It defaults to `justify` in hugo-shortcode-gallery. For your case the `nojustify` should be the right option:

`{{< gallery match="images/*" rowHeight="200" lastRow="nojustify"  >}}`



Here is the corresponding part of Justified-Gallery documentation:

> "Decide to justify the last row (using 'justify') or not (using 'nojustify'), or to hide the row if it can't be justified (using 'hide'). By default, using 'nojustify', the last row images are aligned to the left, but they can be also aligned to the center (using 'center') or to the right (using 'right')." (https://miromannino.github.io/Justified-Gallery/options-and-events/)

**Comment by think-nice-things** [comment]
thanks. `lastRow="nojustify"` does exactly what I wanted.
