### ISSUE TITLE
filtering buttons 

### ISSUE THREAD

**Issue by stiliajohny** [mfg92/hugo-shortcode-gallery#33]
Hi @mfg92 

Nice work on this ! 

I seem to be having some issues with the filtering buttons not showing, 

when I check out your example-site and render it with Hugo the buttons are showing, 

then I take the exact code and add it to mine and it doesn't show the filtering buttons 

Here is my md 
https://github.com/stiliajohny/stiliajohny.github.io/tree/galery/content/photography

here is my `config.toml`
In particular :

gallery anotations
https://github.com/stiliajohny/stiliajohny.github.io/blob/702b64a803c01aaf8277b69d20591175c4d10a3c/config.toml#L249

exiff annotations 
https://github.com/stiliajohny/stiliajohny.github.io/blob/702b64a803c01aaf8277b69d20591175c4d10a3c/config.toml#L559

Am I missing something ?

**Comment by stiliajohny** [comment]
Update, I believe there must be a CSS issue with the `button\` element on my main theme 
after inspecting the page, the buttons are there but not visible

**Comment by stiliajohny** [comment]
Who knew 

the following file was problematic 
https://github.com/mfg92/hugo-shortcode-gallery/blob/865699e9f33637655a701fb811bc20225befce7c/assets/shortcode-gallery/filterbar.sass

In particular, I had to 

```diff 
  button
    padding: 6px
-    border: 1px solid #fff
+
    border-radius: 5px
    background-color: transparent
    font-weight: bold
-    color: #fff
+    color: #000
    line-height: 1em
```

This is due to my main theme having a dark and light theme, which I think it renders the buttons 

Closing the issues as it is not related to this repo

**Comment by stiliajohny** [comment]
here is the override for the CSS inline to the Markdown 

The `.justified-gallery-filterbar button` would need to match the themes CSS element 
Use browser inspect to confirm


```markdown
---
title: "Gallery"
date: 2020-10-21T18:45:32+02:00
draft: false
---

<style>
img {
    box-shadow: inset 10px 10px 60px #fff !important;
    -moz-border-radius:25px !important;
    border-radius:10px !important;
}

.justified-gallery-filterbar button {
    padding: 6px !important;
    border: 1px solid #fff !important;
    border-radius: 5px !important;
    background-color: white !important;
    font-weight: bold !important;
    color: #000  !important;
    line-height: 1em !important;
}
</style>

Coming Soon!

{{< gallery match="*" showExif="true" sortOrder="desc" loadJQuery="true" embedPreview="true" filterOptions="[{label: 'All', tags: '.*'}, {label: 'Amphibian', tags: 'animal|amphibian'}]" >}}
```

**Comment by RidaAyed** [comment]
@stiliajohny 
> when I check out your example-site

what example-site?
