### ISSUE TITLE
showExif displays placeholder text even if tag does not exist.

### ISSUE THREAD

**Issue by carstenstann** [mfg92/hugo-shortcode-gallery#37]
Thanks for the amazing shortcode! It's exactly what I was attempting to build for my site, but better. I found a small bug and have a suggestion below.

---

Inside of the gallery.html the following snippet controls the display image exif data. The problem is that placeholder text such as the 'mm', 'f/', 'sec', and 'ISO' either preceding or following their respective tags is displayed regardless of whether the tag itself is available in the metadata or not. This problem only occurs if `showExif=true` **and** no metadata is available for a given image.

```
{{ if $showExif }}
	data-description="{{ .Model }} + {{ .LensModel }}<br/>{{ .FocalLength }}mm f/{{ .FNumber }} {{ .ExposureTime }}sec ISO {{ .ISOSpeedRatings }}"
{{ end }}
```

This results in the following exif display, for images w/o available metadata ('QSS-32_32' is from the description):
<img width="848" alt="image" src="https://user-images.githubusercontent.com/28669904/150673483-8a7b51d6-a30a-4979-8ca5-50ff0893a980.png">

A simple solution is to wrap each tag's lookup inside a `with` statement:
```
{{ if $showExif }}
	data-description="{{with .Model}}{{ . }}{{end}}{{with .LensModel}} {{ . }}{{end}}<br/>{{with .FocalLength}} {{ . }}mm{{end}}{{with .FNumber}} f/{{ . }}{{ end }}{{with .ExposureTime}} {{ . }}sec{{end}}{{with .ISOSpeedRatings }} ISO {{ . }}{{end}}"
{{ end }}
```
Wrapping tag lookups inside `with` statements only displays them if they are available, which results in the following display of the same image above (again note that 'QSS-32_32' is from the description):
<img width="797" alt="image" src="https://user-images.githubusercontent.com/28669904/150673628-98624215-0b61-4d37-8436-7313db6eeb8d.png">

**Comment by mfg92** [comment]
Thank you @carstenstann  for your detailed bug report and the suggested solution.
I modified your solution a tiny bit. Is your issue solved with the latest version?

**Comment by carstenstann** [comment]
Hi @mfg92, 
2be808e solved the issue on my end. Thanks for implementing the fix!
