### ISSUE TITLE
Nothing appear while using at a blog post or the like

### ISSUE THREAD

**Issue by t0rsten** [mfg92/hugo-shortcode-gallery#38]
Hi, awesome short code. It works while using at a regular page, but while using at a blog post or the like nothing appears any idea?

works:
https://github.com/t0rsten/gallerytest/tree/main/content/about

doesn't
https://github.com/t0rsten/gallerytest/tree/main/content/gallery

**Comment by mfg92** [comment]
Can you try to have your content organized like this:

content
<pre>
content/
├─ gallery1/
│  ├─ images/
│  ├─ index.md
├─ gallery2/
│  ├─ images/
│  ├─ index.md
├─ post_without_gallery.md
├─  ...
</pre>

**Comment by t0rsten** [comment]
When you can't see the forest for the trees! Great, that works. Thank you very much!
