### ISSUE TITLE
How to use the shortcode on the _index homepage?

### ISSUE THREAD

**Issue by RidaAyed** [mfg92/hugo-shortcode-gallery#39]
I get any empty page trying to add the shortcode to `_index.md`. Is this by design?

**Comment by mfg92** [comment]
The underscore in `_index.md` mean that this page belongs to a [Branch Bundle](https://gohugo.io/content-management/page-bundles/).

This has the consequence that the images must be in the same folder as the ` _index.md` file. So the folder structure must be like this:

<pre>
page/
├─ _index.md
├─ image1.jpg
├─ image2.jpg
</pre>

and the shortcode:
`{{< gallery match="*" loadJQuery="true" >}}`
