### ISSUE TITLE
Add support for avif files

### ISSUE THREAD

**Issue by alexvanderberkel** [mfg92/hugo-shortcode-gallery#42]
Hi,

have you tested the shortcode with hugo + extended for avif files?  For me this does not work. Not sure if it is the shortcode or some dependency which is not capable of handling avif files..

hugo v0.92.2+extended linux/amd64 BuildDate=2022-02-23T16:47:50Z VendorInfo=ubuntu:0.92.2-1
Error: Error building site: "~/content/portfolio/Wildlife/index.de.md:7:1": failed to render shortcode "gallery": failed to process shortcode: "~/themes/hugo-shortcode-gallery/layouts/shortcodes/gallery.html:130:30": execute of template failed: template: shortcodes/gallery.html:130:30: executing "shortcodes/gallery.html" at <$original.Fit>: error calling Fit: *resources.genericResource is not an image

**Comment by mfg92** [comment]
Hugo is currently not abled to process AVIF images: https://github.com/gohugoio/hugo/issues/7837

So sadly there is nothing I can do to solve this issue.
