### ISSUE TITLE
Gallery not shown in index.md

### ISSUE THREAD

**Issue by dk-do** [mfg92/hugo-shortcode-gallery#46]
Hi everybody!
I am currently a bit struggling with setting up the gallery.
I use the [hugo-coder](https://github.com/luizdepra/hugo-coder) theme and want to add the gallery as an add on.
I‘ve walked through the quickstart guide of the gallery, but when I add the example code, it‘s just shown as a text when I access the md-file…

**Comment by mfg92** [comment]
Your theme does not use jQuery. Thus you have to tell hugo-shortcode-gallery to use the supplied jQuery. To do so, you either set `loadJQuery=true` wherever you use the shortcode, or you set `galleryLoadJQuery=true` in your project configuration file (toml/yaml).

**Comment by dk-do** [comment]
Do you mean in the shortcode-gallery config.toml or in the one of the theme?

**Comment by mfg92** [comment]
I mean the your [site's config file](https://gohugo.io/getting-started/configuration/#configuration-file)

**Comment by dk-do** [comment]
Good morning!
I tried this, but I got still just:

![image](https://user-images.githubusercontent.com/61822901/179687799-cb822677-65b9-4650-a756-fe9dcd2b1a6e.png)

**Comment by dk-do** [comment]
Okay - my fault. I've got it (typo).
