### ISSUE TITLE
Configuring gallery to work with branch bundles?

### ISSUE THREAD

**Issue by hamhoagie** [mfg92/hugo-shortcode-gallery#5]
Hello - I was wondering if it were possible to use the shortcode in a branch bundle page. I'm new to Hugo, and how it handles content; I'd like to use the shortcode on my _index.md page that's the root of my content directory. Is this currently possible?

**Comment by mfg92** [comment]
Hi,

I have tried the following and it worked:

Folder structure:
```
content/
├──posts
│   └── ...
├── img_01.png
└── _index.md
```
_index.md:
```
## Hello 
{{< gallery match="img_*" rowHeight="150" loadJQuery="true" >}}
```

Does that help answer your question?

**Comment by hamhoagie** [comment]
hello!  thank you so much for your help, that worked perfectly.
