### ISSUE TITLE
Gallery layout not working properly with Congo theme

### ISSUE THREAD

**Issue by sjohner** [mfg92/hugo-shortcode-gallery#50]
Hi

First of all thank you for providing and maintaining this component!

I was able to setup a gallery but struggle with the layout. I am using the [Congo theme](https://github.com/jpanther/congo) and above a certain resolution (width > 1023px) somehow the images of the gallery do not align as intended. Instead of being displayed as a gallery, they are simply displayed one by one below each other and the rowHeight parameter has no effect on the gallery anymore. Below 1024px the gallery works as expected. Any idea what causes this behaviour?

<img width="808" alt="Screenshot 2022-10-03 at 00 52 27" src="https://user-images.githubusercontent.com/16019080/193479867-48c8cedc-19ac-44ac-ad1d-af804365dfcd.png"> <img width="811" alt="Screenshot 2022-10-03 at 00 53 13" src="https://user-images.githubusercontent.com/16019080/193479893-8006094d-53ce-4caa-b20e-73a774deee2a.png">

Thanks for your support!

**Comment by mfg92** [comment]
Hi,

without having access to the webpage with the issue it is hard to analyze what causes the problem.  I guess it has something to do with these lines of CSS https://github.com/jpanther/congo/blob/dev/assets/css/compiled/main.css#L3112-L3158. You could try to comment them out to check.

**Comment by sjohner** [comment]
Thanks for the feedback! Commenting these lines does indeed seem to work. But I'm not sure what else this will break :-) Maybe @jpanther as the author of the Congo theme can shed more light on this?

**Comment by mfg92** [comment]
I am closing the ticket now, as the problem cannot be solved from this project's side. Feel free to reopen it if I can help in any way.
