### ISSUE TITLE
How to use with Wowchemy theme?

### ISSUE THREAD

**Issue by altosys** [mfg92/hugo-shortcode-gallery#51]
I'm trying to use this gallery with the Wowchemy theme, but the problem is that the theme has a builtin shortcode with the same name, i.e. `{{< gallery ... >}}`. So I tried to set up the gallery from this repo by copying the `layouts/shortcodes`, `assets/shortcode-gallery` and `static/shortcode-gallery` into my project, and renaming the shortcode file to `autogallery.html` instead.

This does load when I start up the hugo server, but the gallery doesn't function properly, all the thumbnails are just shown as very blurred images, and the thumbnails just link directly to the image files, i.e. there is no lightbox opening or anything like that.

What steps am I missing in order to get this to work as a manually imported shortcode?

**Comment by mfg92** [comment]
Are there any issues logged in your browsers console?

**Comment by altosys** [comment]
Yeah I can see one error in the console: `Uncaught ReferenceError: jQuery is not defined`

**Comment by altosys** [comment]
@mfg92 did you have any input on the above?

**Comment by flewid** [comment]
I too am experiencing this same error any ideas?

**Comment by mfg92** [comment]
Does your site already include jQuery?

**Comment by flewid** [comment]
it does yes, i tried with the LoadJQuery=true, and without. I get the same error as @altosys when including it manually.

**Comment by jpfeuffer** [comment]
Same issue here! Same error. With `loadJQuery=true` and without.

**Comment by jpfeuffer** [comment]
The following post solved my problem, as I was using exactly the massively theme. https://github.com/mfg92/hugo-shortcode-gallery/issues/19

Since your errors are the same, I expect that your theme is using jquery as well and loads it at an incompatible place.
