### ISSUE TITLE
Hello, I would like to ask if it can only be used in index files, because I find that it does not work in other files.

### ISSUE THREAD

**Issue by huoranger** [mfg92/hugo-shortcode-gallery#52]
Hello, I would like to ask if it can only be used in index files, because I find that it does not work in other files.

**Comment by mfg92** [comment]
Yes, because it uses [page bundles](https://gohugo.io/content-management/page-bundles/). In many cases you can replace a "normal" markdown file by a folder, and but an indexfile with the content into it.
