### ISSUE TITLE
Gallery seems to generate but doesn't display anything

### ISSUE THREAD

**Issue by no-budy** [mfg92/hugo-shortcode-gallery#54]
I installed the theme and put the images that I was testing in an images folder but it doesn't seem to be able to find them. 
![image](https://user-images.githubusercontent.com/75763144/215870737-3077b49d-1efc-4d8d-a90a-9bd8ba5577dd.png)
I keep getting this error from this. 
![image](https://user-images.githubusercontent.com/75763144/215870852-dff00e2f-0bf8-476b-a455-3126421d3b40.png)
Here is how I'm calling the shortcode and what the file structure looks like.
![image](https://user-images.githubusercontent.com/75763144/215871036-2168222c-ff75-4e8d-9dfb-8ef1ffe1f394.png)
![image](https://user-images.githubusercontent.com/75763144/215871205-b292c130-fc99-41b1-906a-21e0fef7591f.png)
The shortcode is in the melee.md file and the images are located in that images file

**Comment by no-budy** [comment]
![image](https://user-images.githubusercontent.com/75763144/215871888-7b76ecc2-aac3-41df-9282-3adb52fad414.png)
Here is an image of the HTML that is rendered

**Comment by mfg92** [comment]
You need to organize your markdown file and the images in a  [page bundle ](https://gohugo.io/content-management/page-bundles/). The file structure in your case should look like this:
```
melee
   |- images
   |   |-image01.jpg
   |   |-anotherImage.png
   |- index.md
startingWithHugo.md
```

**Comment by mfg92** [comment]
Feel free to reopen this issue if it still does not work as expected.
