### ISSUE TITLE
Repository does not specify the license conditions for this software

### ISSUE THREAD

**Issue by dgoodwin** [mfg92/hugo-shortcode-gallery#56]
Hi, I was just wondering if you could specify a license for the code in this repo. I have some derivative code I would like to either build upon this or possibly submit to this repo if you were open to it, but can't really do that in absence of knowing the license of the software. 

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks so much for writing this shortcut, it's the best option for hosting images with hugo I've found and has helped me a lot.

**Comment by mfg92** [comment]
Hi,
thank you for this reminder, adding a lizenez is long overdue. I'm not sure which one I should choose. I tend towards using the MIT license. All the dependencies of this project use MIT.

Do you have any concerns? Tips are welcome

**Comment by dgoodwin** [comment]
MIT sounds pretty good to me for a project like this, Apache 2 would be the other that comes to mind but it sounds like that's mostly just if you wanted protection for a patent license. MIT seems like a good way to go.

Thanks so much!

**Comment by mfg92** [comment]
I decided to go with MIT:
