### ISSUE TITLE
Docs: minimal hugo site implementing the gallery

### ISSUE THREAD

**Issue by martinctc** [mfg92/hugo-shortcode-gallery#7]
Hi there,
Thank you so much for setting up this gallery. It would be extremely helpful if you could provide a minimal hugo repo with this gallery implemented, as I am experiencing issues making the gallery display properly. I don’t think there is a bug but more about me having missed a crucial step which I couldn’t troubleshoot on my own. Thank you - have added this as a documentation enhancement.

**Comment by mfg92** [comment]
I have created an example site in a new branch _example_site_ (https://github.com/mfg92/hugo-shortcode-gallery/tree/example_site).
Can you check if it works for you? Does it help you understand how to use hugo-shortcode-gallery?

**Comment by martinctc** [comment]
Thank you! 

For a bit of context - the issue I was struggling with actually was the gallery simply not showing up on my page despite following all the steps, and I was unable to pinpoint whether this was due to the way I set up `config.toml`, or the Page/Branch bundles, or something else, and I had to go through element to figure out what the problem was. I was ultimately able to troubleshoot the issue, which was actually due to the Javascript not being loaded when the shortcode was run. I managed to make it work via trial-and-error by tweaking the shortcode (apologies as I'm probably not knowledgeable enough to explain the solution at this point yet). In short, the example site you set up would be really helpful as it could help future users pinpoint issues much quicker!

I have one additional small ask - would you be able to add an example of the JSON file for adding ImageDescription and also the tweaks you made to your `config.toml`, to your example site? This will make these features much more easy to implement (as I'm still figuring out how to do them properly). Thank you again for this great theme component / shortcode!

**Comment by mfg92** [comment]
I have updated the example site. Please have a look and check if it helps you.
It would be very nice if you can use your gathered knowledge (and your perspective of somebody who just has started working with hugo-shortcode-gallery) to improve the documentation (README.md) and make a pull request :)

**Comment by archphile** [comment]
@martinctc please can you share your final shortcode? I am using hugo with sam theme and until now it has been impossible to show the gallery on the desired page.

Thanks in advance.

**Comment by martinctc** [comment]
This is awesome! Thank you. I think the `meta` file helps a lot. Happy to make a PR to improve the documentation :)
