### ISSUE TITLE
[Info] Updating hugo from 1.21 to 1.23 breaks softlinked images

### ISSUE THREAD

**Issue by RidaAyed** [mfg92/hugo-shortcode-gallery#74]
Updating hugo from 1.21.2 to 1.23.8 leads to disappearance of softlinked images in the gallery.

Downgrading back to 1.21.2 solves the issue.

A quick search for `link`,`soft` returned zero results here: https://github.com/gohugoio/hugo/releases

**Comment by mfg92** [comment]
This is an intentional change by Hugo, see: 
- https://discourse.gohugo.io/t/symlinks-not-more-followed-in-0-123/48594/3
- https://github.com/gohugoio/hugo/issues/11556

I am closing this issue as there is nothing I can do on my end.
