### ISSUE TITLE
Captions on Thumbnails ?

### ISSUE THREAD

**Issue by Phil89a** [mfg92/hugo-shortcode-gallery#75]
Just managed to get this working with Blowfish theme and it is looking great.

Is it possible to include captions on the gallery thumbnails using Justified Gallery's Caption option - see https://miromannino.github.io/Justified-Gallery/captions/ ?

Thanks

**Comment by mfg92** [comment]
I have made a small change that will allow you to configure the captions.

To enable the caption, add the parameter _justifiedGalleryParameters_ with the value `"captions: true"`:
```
{{< gallery
    justifiedGalleryParameters="captions: true"
>}}
```

Or if you want to configure the captions:
```
{{< gallery
    justifiedGalleryParameters="captions: true, captionSettings: {animationDuration: 500, visibleOpacity: 0.9, nonVisibleOpacity: 0.0}, cssAnimation: false"
>}}
```

With this mechanism, one can set all options that [Justified Gallery supports](https://miromannino.github.io/Justified-Gallery/options-and-events/).

There is no release with this change yet, it is only in the main branch. Please test it and give me feedback.

**Comment by Phil89a** [comment]
Magic thanks - will try it out and let you know

**Comment by Phil89a** [comment]
Working perfectly.   Many thanks

**Comment by mfg92** [comment]
Good to hear that, ty for the feedback!
