### ISSUE TITLE
How to opt out of downscaling of the thumbnail image?

### ISSUE THREAD

**Issue by thecoducer** [mfg92/hugo-shortcode-gallery#77]
`thumbnailResizeOptions` uses the Hugo's Fit method which downscales the thumbnail image. I don't want image to be downscaled or any compromise to the image quality. How can I stop this image resizing thing or at least the downscaling?

**Comment by mfg92** [comment]
On the master branch I have implemented two new options for `thumbnailResizeOptions`:

- _original_: Use the original image (without scaling or other modifications).
- _full_: Use the same image as the lightbox will show when clicked. Scaling may be applied depending on whether `imageResizeOptions` is used.

It would be nice if you could give me some feedback on whether or not this is working for you.

**Comment by thecoducer** [comment]
Hey @mfg92 , it is working as expected. Thanks for the enhancement.
