### ISSUE TITLE
Gallery shortcode not working 

### ISSUE THREAD

**Issue by thedivtagguy** [mfg92/hugo-shortcode-gallery#8]
I'm trying to incorporate the shortcode in my website. I've followed the instructions as they stand. 

I've edited my `config.yaml` to this: 

```
theme: 
    - hugo-theme-novela
    - hugo-shortcode-gallery
baseURL: "https://example.com"
languageCode: "en-us"
```

I've also cloned it into the `themes` folder. According to the installation instructions, this should be enough to get me started. However when I add a new folder called `images` next to the `_index.md` inside content and us this shortcode, nothing shows up: 

```
---
hero:
  heading: A Whole Sort of General Mishmash
  maxWidthPX: 400
seo:
  image: /images/hero-2.jpg
---
{{< gallery match="images/*" sortOrder="desc" rowHeight="150" margins="5" resizeOptions="600x300 q90 Lanczos" showExif="true" previewType="blur" embedPreview="true" >}}
 ```

I've uploaded all the files to this repo here if that helps: [Website Repo](https://github.com/thedivtagguy/website). Can someone help me with this? I've been trying for a while now. I'm new to Hugo so I might be missing something that is very simple.

**Comment by thedivtagguy** [comment]
Hey I'm so sorry, I think there was some problem with the partials in one of the pages. I've rebuilt it and uploaded to this repo: https://github.com/thedivtagguy/gallery, does this work now? 

I have tried looking at the example site but I think there's something I'm missing that I can't quite place. I shall try again though and share what I'm doing.

**Comment by mfg92** [comment]
I made it work, see my commits and commit messages:
https://github.com/mfg92/gallery/commits/master

**Comment by thedivtagguy** [comment]
Oh wow, this works wonderfully! I shall submit an issue with the theme's authors to update the JQuery. I have a couple of more follow-up questions if that is fine: 

1. After I've merged this fork and updated my local copy, will I have to keep removing the references to the old Jquery for every post? Or have you managed to remove it for good? 

2. The image thumbnails look a little blurry right now. I tried removing `previewType="blur"` but this makes the gallery itself disappear. How can I fix this?

![image](https://user-images.githubusercontent.com/6006888/102848395-c0e5a700-443a-11eb-9ec3-537e69009cee.png)

3. I wish to keep the gallery in my homepage, but apparently page resources for _index.md need to live in the same directory as the _index.md, i.e. not in a subdir. Here: https://gohugo.io/content-management/page-bundles/ So I can't have a separate folder for galleries, but how would I call it in the shortcode? 

I've tried this and it didn't work: 

`{{< gallery match="/*" sortOrder="desc" rowHeight="150" margins="5" resizeOptions="600x300 q90 Lanczos" showExif="false" previewType="blur" embedPreview="true" >}}`

Thank you again for your help. This is a wonderful project!

**Comment by mfg92** [comment]
1. You will need to remove them for every post where you want to use hugo-shortcode-gallery
2. You need to play arround with _resizeOptions_, use a value like "600x600 q90 Lanczos". _resizeOptions_ defines the resolution of the image in the gallery (when you click on an image, the full resolution will be used). _previewType_ come only to play when _embedPreview_ is set to true, then it will either include a single pixel or a very small preview image directly in the in the HTML file. The brower can show these embedded pixels or images directly without speeking to the server a scond time. In the background the browser will load the resized images and show them as soon as one is available.
3. Do I understand you correctly, wou want to have a gallery in _content/_index.md_? I tried it, but even if you put plain text into this file it is not displayed .

**Comment by thedivtagguy** [comment]
I figured out why the plain text wasn't being rendered! The index.html didn't have `{{ .Content }}` so the text or any content never got rendered. I've fixed it in the main repo and reuploaded with the changes: https://github.com/thedivtagguy/gallery/

If you can just show me how to make this work here with the file path not being a subdir, I would be really glad (and out of your hair!). Sorry for the prolonged queries. 

I'll also create a suggestion with the theme's authors to update the JQuery, that can't be good in any case.

**Comment by mfg92** [comment]
Sorry for the big delay...

I pushed some commits to https://github.com/mfg92/gallery/commits/master. These demonstrate how to use images stored directly next to the mardown file.

FYI.: If the shortcode does not have "match" as an parameter, all images (in subdirectories or not) will be displayed.
