### ISSUE TITLE
failed to extract shortcode

### ISSUE THREAD

**Issue by hugo-mcfrojd** [mfg92/hugo-shortcode-gallery#83]
I am using Method A to install the gallery but when i run `hugo serve` I get this error: 

`failed to extract shortcode: shortcode "gallery" must be closed or self-closed`

and it points to the line in the code in index.md that have the shortcode.

Anyone else have this problem or maybe someone knows whats wrong?

**Comment by hugo-mcfrojd** [comment]
I am using the theme Beautifulhugo if that is to any help.

I tried this gallery a year ago together with the papermod theme and that worked fine then.

**Comment by mfg92** [comment]
Can you show the markdown file where you include the gallery?

**Comment by hugo-mcfrojd** [comment]
I see that the beautifulhugo theme already have a `{{< gallery >}}` shortcode. ( https://hugo-theme-beautifulhugo.netlify.app/post/2017-03-20-photoswipe-gallery-sample/ )

Since i run the theme & your gallery both as a module i guess there will be some collisions when they are named the same.
Or is there a way to disable the themes shortcode when you run it as a module?

Im hosting the site on cloudflare pages.

**Comment by mfg92** [comment]
The first solution that comes to my mind is to fork this repository and rename the short code by renaming the file _hugo-shortcode-gallery/layouts/shortcodes/gallery.html_.

**Comment by mfg92** [comment]
I'm closing this issue as I haven't heard anything for a while, but feel free to open the ticket again
