### ISSUE TITLE
Is there a way to limit the number of images loaded?

### ISSUE THREAD

**Issue by rpapallas** [mfg92/hugo-shortcode-gallery#85]
If a gallery contains numerous images, is there an option to limit the number of images that appear on page load? I am thikning of `onPageLoadLimit="10"`. It would be great to have this option to help pages load faster and have a button “load all” underneath to load all of them should the visitor want to see the entire gallery.

If that's of interest, I could look into implementing it at some point.

**Comment by mfg92** [comment]
> If previewType is set to "blur" (or "color"), a very low resolution image (or a single pixel image) will be loaded for every image in the gallery first. The hight resolution thumbnail images (see thumbnailResizeOptions) will only be loaded if they are on the currently visible part of the page (or close to it). This leads to a faster loading page. You can set previewType to "none" to disable this feature and all thumbnails will be directly loaded. 
[[README](https://github.com/mfg92/hugo-shortcode-gallery?tab=readme-ov-file#usage-example)]

Is this what you need?

**Comment by rpapallas** [comment]
That seems to take care of my concern, yes! Thank you.
