### ISSUE TITLE
Gallery first image loads, but next image is blank

### ISSUE THREAD

**Issue by hawshemi** [mfg92/hugo-shortcode-gallery#88]
When using the Hugo Shortcode Gallery (both locally and deployed on Cloudflare), the gallery works fine for the first image. However, when opening the first image in the gallery and clicking "Next," the following photo does not load, and the screen is blank.

You can test the issue at this live site: https://kezab.ir/  (https://github.com/hawshemi/Kezab-Website) . Visit the gallery and try navigating between images to reproduce the issue.

### Steps to Reproduce:
Set up the Hugo Shortcode Gallery on a Hugo site + Hextra theme.
Open the site locally or on Cloudflare.
Click on the first image in the gallery to open it.
Use the "Next" button to navigate to the second image.

### Expected Behavior:
Each image in the gallery should load sequentially when navigating between images.

### Actual Behavior:
The first image loads correctly, but clicking "Next" shows a blank screen instead of the next image.

### Environment:
Hugo version: It doesn't matter; it appears in all versions as I tested after v0.133.0
Theme/Repo: Hextra theme; It doesn't matter; it appears in all versions as I tested after v0.8.1
Deployment: Tested both locally and on Cloudflare (deployed site: https://kezab.ir/)

### Additional Info:
No error messages appear in the browser console.
Image paths are verified to be correct.
Tested on Chrome/Firefox Windows/Android with the same result.

**Comment by mfg92** [comment]
Hi,
I have tried to reproduce your problem on your [website](https://kezab.ir/gallery/), but everything works as expected there:

![test](https://github.com/user-attachments/assets/bcee3093-727c-4037-8a60-37b410a53d4f)

**Comment by hawshemi** [comment]
Wow, After a couple of hours, it's working :))
I guess it's because of some caching.

Anyhow, thanks for your excellent work.
